[project]
name = "my-crawl4ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crawl4ai>=0.7.7",
    "yt-dlp[curl-cffi,default]>=2025.11.12",
]
